export type MapHas = (value: any) => boolean;
export declare function toString(value: any): string;
export declare function isArray(value: any): boolean;
export declare function isUndef(value: any): boolean;
export declare function isDef(value: any): boolean;
export declare function isTrue(value: any): boolean;
export declare function isFalse(value: any): boolean;
export declare function hasOwn(obj: object, key: string): boolean;
export declare const isObject: (value: any) => boolean;
export declare const isFunction: (value: any) => boolean;
export declare function isPlainObject(value: any): boolean;
export declare function isRegExp(value: any): boolean;
export declare const isString: (value: any) => boolean;
export declare const sleep: (ms: number) => Promise<unknown>;
export default function makeMap(str: string, lowerCase?: boolean): MapHas;
export declare function isReservedTag(value: any): boolean;
export declare const isHTMLTag: MapHas;
export declare const isSVG: MapHas;
export declare const isEqual: (value1: any, value2: any) => boolean;
