name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.3.1

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          
      - run: pnpm install

      - name: Run unit tests
        run: pnpm run ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
